"""Type stubs for lxml.etree"""

from typing import Any, Iterator, List, Optional, Union, Dict, Tuple, Sequence, Sized, Iterable

class _Element:
    tag: str
    attrib: Dict[str, str]
    text: Optional[str]
    tail: Optional[str]
    nsmap: Dict[Optional[str], str]
    
    def find(self, path: str, namespaces: Optional[Dict[str, str]] = None) -> Optional['_Element']: ...
    def findall(self, path: str, namespaces: Optional[Dict[str, str]] = None) -> List['_Element']: ...
    def xpath(self, path: str, namespaces: Optional[Dict[str, str]] = None, **kwargs: Any) -> Any: ...
    def iterchildren(self, tag: Optional[str] = None) -> Iterator['_Element']: ...
    def itersiblings(self, preceding: bool = False) -> Iterator['_Element']: ...
    def getparent(self) -> Optional['_Element']: ...
    def getroottree(self) -> '_ElementTree': ...
    def get(self, key: str, default: Optional[str] = None) -> Optional[str]: ...
    def set(self, key: str, value: str) -> None: ...
    def append(self, element: '_Element') -> None: ...
    def insert(self, index: int, element: '_Element') -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> '_Element': ...
    def __iter__(self) -> Iterator['_Element']: ...

class _Comment(_Element): ...

class _ProcessingInstruction(_Element): ...

class _Entity(_Element): ...

class _ElementUnicodeResult(_Element): ...

class _ElementTree:
    def getroot(self) -> _Element: ...
    def parse(self, source: Any) -> '_ElementTree': ...
    def iter(self, tag: Optional[str] = None) -> Iterator[_Element]: ...

class _XMLParser:
    def __init__(self, remove_blank_text: bool = False, encoding: Optional[str] = None, **kwargs: Any): ...

class HTMLParser(_XMLParser): ...

class XMLSyntaxError(Exception): ...

def Element(_tag: str, attrib: Optional[Dict[str, str]] = None, nsmap: Optional[Dict[str, str]] = None, **extra: Any) -> _Element: ...
def SubElement(parent: _Element, _tag: str, attrib: Optional[Dict[str, str]] = None, nsmap: Optional[Dict[str, str]] = None, **extra: Any) -> _Element: ...
def parse(source: Any, parser: Optional[_XMLParser] = None) -> _ElementTree: ...
def fromstring(text: Union[str, bytes], parser: Optional[_XMLParser] = None) -> _Element: ...
def tostring(element: _Element, encoding: str = ..., method: str = 'xml', **kwargs: Any) -> Union[bytes, str]: ...
def QName(text: Any) -> Any: ...
